import { NextResponse } from 'next/server'
import { generateCorrelationId } from '@/lib/services/logger'

// ---------------------------------------------------------------------------
// RFC 9457 Problem Details – core type & helpers
// ---------------------------------------------------------------------------

/**
 * RFC 9457 compliant Problem Details structure extended with Spideryarn-specific
 * fields. All error responses emitted by API routes should conform to this
 * interface.
 */
export interface ProblemDetail {
  /** A URI reference that identifies the problem type. */
  type: string
  /** Short, human-readable summary of the problem. */
  title: string
  /** HTTP status code generated by the origin server. */
  status: number
  /** Human-readable explanation specific to this occurrence. */
  detail?: string
  /** Absolute URI that identifies the specific occurrence. */
  instance?: string
  /** Correlation ID to link logs & tracing information. */
  correlationId: string
  /** Indicates if the operation can be retried safely. */
  retryable?: boolean
  /**
   * Arbitrary extension members providing additional context. RFC 9457 permits
   * custom members, so we allow any additional properties.
   */
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  [key: string]: any
}

/**
 * Base class for all application-level errors. These map 1-to-1 to
 * `ProblemDetail` responses and can be thrown within business logic. API routes
 * should catch them and convert via `createProblemDetail()`.
 */
export class ApplicationError extends Error {
  constructor(
    /** Stable code identifier (e.g. DOCUMENT_NOT_FOUND) */
    public readonly code: string,
    message: string,
    /** Optional structured context used for logging & debugging. */
    public readonly context: Record<string, unknown> = {},
    public readonly cause?: Error
  ) {
    super(message)
    this.name = code
  }
}

// ---------------------------------------------------------------------------
// Domain-specific subclasses (thin wrappers for now)
// ---------------------------------------------------------------------------
export class DocumentError extends ApplicationError {}
export class StorageError extends ApplicationError {}
export class AIServiceError extends ApplicationError {}
export class ValidationError extends ApplicationError {}

// ---------------------------------------------------------------------------
// Helper utilities
// ---------------------------------------------------------------------------

/** Convenience type-guard useful in callers and tests. */
export function isProblemDetail(x: unknown): x is ProblemDetail {
  return (
    !!x &&
    typeof x === 'object' &&
    'type' in x &&
    'title' in x &&
    'status' in x &&
    'correlationId' in x
  )
}

/**
 * Create a `NextResponse` containing a serialized Problem Detail object and
 * ensure the `x-spideryarn-correlation-id` header is set.
 */
export function createProblemDetail(opts: Omit<ProblemDetail, 'correlationId'> & { correlationId?: string }): NextResponse {
  // Allow caller to omit correlationId – we'll generate one if absent.
  const correlationId = opts.correlationId ?? generateCorrelationId()

  // Type assertion is safe here because `opts` is guaranteed (by the
  // function signature) to contain all required ProblemDetail keys except
  // `correlationId`, which we inject just below.
  const body = { ...opts, correlationId } as ProblemDetail

  const res = NextResponse.json(body, { status: body.status })
  res.headers.set('x-spideryarn-correlation-id', correlationId)
  return res
}

// ---------------------------------------------------------------------------
// Convenience helpers for common Problem Detail variants
// ---------------------------------------------------------------------------

/** Map HTTP status → short human-readable title. Centralised so all routes stay consistent. */
export function getErrorTitle(status: number): string {
  switch (status) {
    case 400: return 'Bad Request'
    case 401: return 'Unauthorized'
    case 403: return 'Forbidden'
    case 404: return 'Not Found'
    case 408: return 'Request Timeout'
    case 409: return 'Conflict'
    case 413: return 'Payload Too Large'
    case 422: return 'Unprocessable Entity'
    case 429: return 'Too Many Requests'
    case 500: return 'Internal Server Error'
    case 502: return 'Bad Gateway'
    case 503: return 'Service Unavailable'
    case 504: return 'Gateway Timeout'
    default: return 'Unknown Error'
  }
}

// ---------------------- Tool-specific wrapper ------------------------------

/** RFC 9457 Problem Detail that always includes a `toolId` extension member. */
export interface ToolProblemDetail extends ProblemDetail {
  toolId: string
}

/** Create a typed Problem Detail for the unified Tool API routes. */
export function createToolProblemDetail(
  opts: Omit<ToolProblemDetail, 'correlationId'> & { correlationId?: string }
): NextResponse {
  // If caller omitted `title`, derive it from status code for convenience.
  const title = opts.title ?? getErrorTitle(opts.status)

  return createProblemDetail({ ...opts, title })
} 