import type { HeadingOperation } from '@/lib/prompts/schemas/headings'
import type { Mutation, DocumentTransform } from '@/lib/types/mutation'
import { generateContentBasedId } from './deterministicId'

/**
 * Convert a set of HeadingOperation objects into a Mutation that can be
 * executed via the MutationEngine. At present we handle insert and replace
 * operations. Remove operations are passed through as-is. Modify operations
 * are not generated by the headings tool.
 */
export function headingOperationsToMutation(options: {
  documentId: string
  operations: HeadingOperation[]
  mutationId?: string
}): Mutation {
  const { documentId, operations, mutationId } = options

  const forward: DocumentTransform[] = []
  const reverse: DocumentTransform[] = []

  operations.forEach((op, index) => {
    switch (op.action) {
      case 'insert': {
        if (!op.content || !op.insertNewBeforeExistingId) return
        // If the operation already carries a deterministic id (persisted in the
        // database) we *must* reuse it so that later remove/replace operations
        // target the correct element when we replay a cached history.  Only
        // fall back to content-based generation for legacy rows that have no id.
        const headingId = op.content.id
          ? op.content.id
          : generateContentBasedId(
              documentId,
              'heading',
              `${op.content.content}:before:${op.insertNewBeforeExistingId}:${index}`
            )

        const insertTransform: DocumentTransform = {
          action: 'insert',
          insertNewBeforeExistingId: op.insertNewBeforeExistingId,
          content: {
            id: headingId,
            tag_name: op.content.tag_name,
            content: op.content.content,
            attributes: {
              'class': 'syr-ai-generated',
              'data-ai-generated': 'true'
            }
          }
        }
        const removeReverse: DocumentTransform = {
          action: 'remove',
          targetId: headingId
        }
        forward.push(insertTransform)
        reverse.unshift(removeReverse) // ensure reverse order
        break
      }
      case 'replace': {
        if (!op.content || !op.targetId) return
        const replaceTransform: DocumentTransform = {
          action: 'replace',
          targetId: op.targetId,
          content: {
            tag_name: op.content.tag_name,
            content: op.content.content,
            attributes: {
              'data-ai-modified': 'true'
            }
          }
        }
        // For reverse we would need original content; we can't fetch it here.
        // Create a no-op reverse so mutation engine can still revert (will just leave content).
        const noopReverse: DocumentTransform = {
          action: 'replace',
          targetId: op.targetId,
          content: {
            tag_name: op.content.tag_name,
            content: op.content.content
          }
        }
        forward.push(replaceTransform)
        reverse.unshift(noopReverse)
        break
      }
      case 'remove': {
        if (!op.targetId) return
        const removeTransform: DocumentTransform = {
          action: 'remove',
          targetId: op.targetId
        }
        forward.push(removeTransform)
        // No reverse – we don't have original content.
        break
      }
    }
  })

  return {
    id: mutationId || `heading-ops-${Date.now()}`,
    type: 'insert-headings',
    forward,
    reverse,
    metadata: {
      description: 'AI-generated heading operations',
      generatedHeadingCount: operations.length,
      timestamp: Date.now()
    }
  }
} 