/**
 * Finalise Vision Document API endpoint
 * 
 * This is the final step in the Phase 2 vision-based PDF processing pipeline.
 * It receives the assembled HTML document and metadata from the browser after
 * all pages have been processed and images uploaded directly to Supabase Storage.
 * 
 * The endpoint:
 * 1. Validates that all expected assets are present
 * 2. Creates the document record with the assembled HTML
 * 3. Enqueues the document for shared processing (text extraction, enhancements, etc.)
 */

import { NextRequest, NextResponse } from 'next/server'
import { createProblemDetail } from '@/lib/api/error-utils'
import { createClient } from '@/lib/supabase/server'
import { DocumentService } from '@/lib/services/database/documents'
import { documentAssetsService } from '@/lib/services/database/document-assets'
import { requireAuth } from '@/lib/auth/server-auth'
import { processHtmlToDocument, handleSanitizationError, sanitizeAndExtractText } from '@/lib/services/html-document-processor'
import { createRequestLogger, generateCorrelationId } from '@/lib/services/logger'
import { z } from 'zod'
import { sanitizeDocumentTitle } from '@/lib/utils/document-title'
import { generateSlug } from '@/lib/utils/slug'

// Request body schema
const FinalisationRequestSchema = z.object({
  documentId: z.string().uuid('Invalid document ID format'),
  html: z.string().min(1, 'HTML content is required'),
  pageCount: z.number().int().positive('Page count must be a positive integer'),
  title: z.string().min(1, 'Document title is required'),
  filename: z.string().min(1, 'Filename is required'),
  isPublic: z.boolean().default(false)
})

export async function POST(request: NextRequest) {
  const correlationId = generateCorrelationId()
  const requestLogger = createRequestLogger('/api/finalise-vision-document', correlationId)
  
  try {
    // Validate authentication
    const user = await requireAuth()
    
    requestLogger.info({
      method: 'POST',
      userId: user.id,
      userEmail: user.email
    }, 'Vision document finalisation request initiated')

    // Parse and validate request body
    const body = await request.json()
    const validationResult = FinalisationRequestSchema.safeParse(body)
    
    if (!validationResult.success) {
      requestLogger.warn({
        correlationId,
        errors: validationResult.error.errors,
        userId: user.id
      }, 'Request validation failed')
      
      return createProblemDetail({
        type: '/errors/validation',
        title: 'Invalid request data',
        status: 400,
        detail: 'Request validation failed',
        issues: validationResult.error.errors,
        correlationId
      })
    }
    
    const { documentId, html, pageCount, title, filename, isPublic } = validationResult.data
    
    requestLogger.info({
      correlationId,
      documentId,
      htmlLength: html.length,
      pageCount,
      title,
      filename,
      isPublic
    }, 'Processing document finalisation')
    
    // Initialize Supabase client
    const supabase = await createClient()
    
    // Step 0: Validate page section count against reported pageCount
    {
      // Count <section> wrappers generated by uploader (data-page-number OR pdf-page class)
      const pageSectionMatches = html.match(/<section[^>]+data-page-number="\d+"[^>]*>/g) || []

      const detectedPageCount = pageSectionMatches.length

      if (detectedPageCount !== pageCount) {
        requestLogger.error({
          correlationId,
          documentId,
          detectedPageCount,
          pageCount,
        }, 'FATAL: Mismatch between reported pageCount and number of page sections in HTML')

        return createProblemDetail({
          type: '/errors/page-count-mismatch',
          title: 'Page count mismatch',
          status: 422,
          detail: `Expected ${pageCount} pages but received ${detectedPageCount}. At least one page failed to process.`,
          correlationId,
          documentId,
          detectedPageCount,
          expectedPageCount: pageCount
        })
      }
    }
    
    // Step 1: Validate that the expected number of image assets exist
    requestLogger.info({
      correlationId,
      documentId,
      step: 'asset-validation'
    }, 'Validating document assets')
    
    const documentAssets = await documentAssetsService.getByDocumentIdAndType(documentId, 'image')
    const assetStats = await documentAssetsService.getDocumentAssetStats(documentId)
    
    requestLogger.info({
      correlationId,
      documentId,
      totalAssets: assetStats.totalAssets,
      imageAssets: documentAssets.length,
      expectedPages: pageCount,
      totalStorageSize: assetStats.totalStorageSize
    }, 'Asset validation results')
    
    // Fatal error: If HTML contains images, we must have corresponding assets
    if (assetStats.totalAssets === 0 && html.includes('<img')) {
      requestLogger.error({
        correlationId,
        documentId,
        htmlHasImages: true,
        storedAssets: 0
      }, 'FATAL: HTML contains images but no assets were uploaded to storage')
      
      return createProblemDetail({
        type: '/errors/missing-assets',
        title: 'Missing image assets',
        status: 422,
        detail: 'Images were detected in the document but none were uploaded to storage',
        correlationId,
        documentId,
        expectedImages: 'detected in HTML',
        actualAssets: 0
      })
    }
    
    // Validate that all img tags have valid Supabase Storage URLs
    const imgTags = html.match(/<img[^>]+src="[^"]*"/g) || []
    if (imgTags.length > 0) {
      const invalidImages = imgTags.filter(tag => {
        const srcMatch = tag.match(/src="([^"]*)"/)
        if (!srcMatch) return true
        // srcMatch is defined here - we've already checked it's not null
        const src = srcMatch[1] as string
        // Check if it's a valid Supabase Storage URL for this document
        return !src.includes('/storage/v1/object/public/') || !src.includes(`/${documentId}/assets/`)
      })
      
      if (invalidImages.length > 0) {
        requestLogger.error({
          correlationId,
          documentId,
          totalImages: imgTags.length,
          invalidImages: invalidImages.length,
          sampleInvalidImage: invalidImages[0]
        }, 'FATAL: HTML contains images with invalid storage URLs')
        
        return createProblemDetail({
          type: '/errors/invalid-image-urls',
          title: 'Invalid image URLs',
          status: 422,
          detail: `Found ${invalidImages.length} images with invalid storage URLs`,
          correlationId,
          documentId,
          totalImages: imgTags.length,
          invalidImages: invalidImages.length
        })
      }
    }
    
    // Step 2: Draft handling & duplicate checks
    const documentService = new DocumentService(supabase)
    const existingDocument = await documentService.getById(documentId)

    if (existingDocument && existingDocument.is_draft === null) {
      // A fully-finalised document already exists – return conflict as before
      requestLogger.warn({
        correlationId,
        documentId,
        existingCreatedAt: existingDocument.created_at
      }, 'Document already finalised – preventing duplicate finalisation')

      return createProblemDetail({
        type: '/errors/conflict',
        title: 'Document already finalised',
        status: 409,
        detail: 'Document has already been finalised',
        correlationId,
        documentId,
        slug: existingDocument.slug
      })
    }

    // If a draft row exists we should update it in-place instead of inserting a new row
    const isDraftUpdate = !!existingDocument && existingDocument.is_draft !== null
    
    // Sanitize title early (shared with both flows)
    const sanitizedTitle = sanitizeDocumentTitle(title)

    let processedHtml = html
    let plaintext = ''
    let wordCount = 0
    const slug = existingDocument?.slug ?? generateSlug(sanitizedTitle)

    if (isDraftUpdate) {
      // Re-use the sanitisation + prettification + text extraction helpers from the shared pipeline
      const { prettifiedHtml, plaintext: extractedText } = await sanitizeAndExtractText(
        html,
        requestLogger,
        correlationId
      )

      processedHtml = prettifiedHtml
      plaintext = extractedText
      wordCount = extractedText.trim().split(/\s+/).length

      // Update the existing draft row to final content
      const updated = await documentService.update(documentId, {
        title: sanitizedTitle,
        html_content: processedHtml,
        plaintext_content: plaintext,
        slug,
        is_public: isPublic,
        word_count: wordCount,
        is_draft: null // clear draft flag
      })

      if (!updated) {
        requestLogger.error({ correlationId, documentId }, 'Failed to update draft document during finalisation')
        return createProblemDetail({
          type: '/errors/database',
          title: 'Failed to update draft record',
          status: 500,
          detail: 'Document finalisation failed: could not update draft record',
          correlationId,
          documentId
        })
      }

      requestLogger.info({ correlationId, documentId, step: 'draft-updated' }, 'Draft document updated successfully')

      // Respond success immediately – skip create/insert flow below
      return NextResponse.json({
        success: true,
        document: {
          id: updated.id,
          title: updated.title,
          slug: updated.slug,
          word_count: updated.word_count,
          created_at: updated.created_at
        },
        assets: {
          total: assetStats.totalAssets,
          images: documentAssets.length,
          totalSizeBytes: assetStats.totalStorageSize
        },
        processing: {
          method: 'vision-phase2-finalisation',
          pageCount,
          correlationId
        }
      }, { status: 201 })
    }
    
    // Step 3: Process HTML through shared pipeline with explicit document ID
    requestLogger.info({
      correlationId,
      documentId,
      step: 'shared-pipeline'
    }, 'Processing through shared document pipeline')
    
    const { document } = await processHtmlToDocument(
      html,
      {
        title,
        isPublic,
        filename: filename || 'document',
        provider: 'vision-pipeline',
        correlationId,
        documentId // Pass the explicit document ID
      },
      {
        extractionMethod: 'vision-ai-phase2',
        uploadSource: 'pdf',
        logger: requestLogger,
        userId: user.id,
        supabase
      },
      {
        // Vision pipeline Phase 2 specific metadata
        page_count: pageCount,
        assets_uploaded: assetStats.totalAssets,
        image_assets: documentAssets.length,
        total_storage_bytes: assetStats.totalStorageSize,
        pipeline_phase: 2,
        processing_method: 'client-side-assembly'
      }
    )
    
    // Clear draft flag now that document is fully processed
    try {
      await supabase
        .from('documents')
        .update({ is_draft: null })
        .eq('id', document.id)
    } catch (draftClearErr) {
      requestLogger.warn({
        correlationId,
        documentId,
        error: draftClearErr instanceof Error ? draftClearErr.message : 'unknown'
      }, 'Failed to clear draft flag')
    }
    
    requestLogger.info({
      correlationId,
      documentId: document.id,
      step: 'finalisation-complete'
    }, 'Vision document finalisation completed successfully')
    
    // Return success response
    return NextResponse.json({
      success: true,
      document: {
        id: document.id,
        title: document.title,
        slug: document.slug,
        word_count: document.word_count,
        created_at: document.created_at
      },
      assets: {
        total: assetStats.totalAssets,
        images: documentAssets.length,
        totalSizeBytes: assetStats.totalStorageSize
      },
      processing: {
        method: 'vision-phase2-finalisation',
        pageCount: pageCount,
        correlationId
      }
    }, { status: 201 })

  } catch (error) {
    console.error('Vision document finalisation error:', error)
    
    requestLogger.error({
      correlationId,
      error: error instanceof Error ? error.message : 'Unknown error',
      stack: error instanceof Error ? error.stack : undefined
    }, 'Vision document finalisation error occurred')
    
    // Handle specific errors with clear, debuggable messages
    if (error instanceof Error) {
      if (error.message.includes('Authentication failed') || error.message.includes('User not authenticated')) {
        return createProblemDetail({
          type: '/errors/auth',
          title: 'Authentication required',
          status: 401,
          detail: 'User session expired or invalid. Please log in again.',
          correlationId
        })
      }
      
      if (error.message.includes('Failed to get document assets')) {
        return createProblemDetail({
          type: '/errors/database',
          title: 'Asset validation failed',
          status: 500,
          detail: 'Unable to retrieve document assets from storage. This indicates a database or storage service issue.',
          correlationId
        })
      }
      
      if (error.message.includes('Content sanitization failed') || error.message.includes('sanitization')) {
        const sanitizationError = handleSanitizationError(error, 'pdf')
        return createProblemDetail({
          type: '/errors/sanitization',
          title: 'Sanitization error',
          status: sanitizationError.status,
          detail: sanitizationError.message,
          correlationId
        })
      }
      
      if (error.message.includes('Failed to create document')) {
        return createProblemDetail({
          type: '/errors/database',
          title: 'Document storage failed',
          status: 500,
          detail: 'Unable to store document in database. This indicates a database service issue.',
          correlationId
        })
      }
      
      return createProblemDetail({
        type: '/errors/internal',
        title: 'Document finalisation failed',
        status: 500,
        detail: 'An unexpected error occurred during document processing.',
        correlationId
      })
    }
    
    return createProblemDetail({
      type: '/errors/internal',
      title: 'Unknown error',
      status: 500,
      detail: 'An unknown error occurred during document finalisation',
      correlationId
    })
  }
}

// CORS headers for development
export async function OPTIONS() {
  return new NextResponse(null, {
    status: 200,
    headers: {
      'Access-Control-Allow-Origin': '*',
      'Access-Control-Allow-Methods': 'POST, OPTIONS',
      'Access-Control-Allow-Headers': 'Content-Type',
    },
  })
}