import { z } from 'zod'
import { PromptTemplate } from '../types'

// Schema for planning document critique inputs
export const planningDocCritiqueSchema = z.object({
  planningDocPath: z.string().describe('Path to the planning document being critiqued'),
  planningDocContent: z.string().describe('Full content of the planning document'),
  critiqueMethodology: z.string().describe('Critique methodology from docs/instructions/CRITIQUE_OF_PLANNING_DOC.md'),
  codebaseContext: z.string().describe('Comprehensive codebase context generated by code2prompt (Rust version)'),
})

export type PlanningDocCritiqueInput = z.infer<typeof planningDocCritiqueSchema>

// Prompt template for planning document critique
export const planningDocCritiqueTemplate: PromptTemplate<typeof planningDocCritiqueSchema> = {
  name: 'planning-doc-critique',
  description: 'Generate comprehensive critique of planning documents using codebase context',
  schema: planningDocCritiqueSchema,
  templatePath: 'planning-doc-critique.njk',
  modelConfig: {
    temperature: 0.1,  // Low temperature for consistent, analytical responses
    maxTokens: 4000,   // Allow for comprehensive critique
  },
}