/**
 * Database Type Extensions
 * 
 * This file provides convenience types and manual additions to the auto-generated
 * database types. Import from this file instead of database.ts directly.
 * 
 * The base database-auto-generated.ts file is auto-generated by `npm run db:types` and should
 * not be edited directly as changes will be overwritten.
 */

// Re-export all auto-generated types
export * from './database-auto-generated'
import type { Tables, TablesInsert, TablesUpdate } from './database-auto-generated'

// Convenience types for most commonly used tables
export type Document = Tables<'documents'>
export type DocumentInsert = TablesInsert<'documents'>
export type DocumentUpdate = TablesUpdate<'documents'>

export type Profile = Tables<'profiles'>
export type ProfileInsert = TablesInsert<'profiles'>
export type ProfileUpdate = TablesUpdate<'profiles'>

export type DocumentEnhancement = Tables<'document_enhancements'>
export type DocumentEnhancementInsert = TablesInsert<'document_enhancements'>
export type DocumentEnhancementUpdate = TablesUpdate<'document_enhancements'>

export type AiCall = Tables<'ai_calls'>
export type AiCallInsert = TablesInsert<'ai_calls'>
export type AiCallUpdate = TablesUpdate<'ai_calls'>

export type ChatThread = Tables<'chat_threads'>
export type ChatThreadInsert = TablesInsert<'chat_threads'>
export type ChatThreadUpdate = TablesUpdate<'chat_threads'>

export type ChatMessage = Tables<'chat_messages'>
export type ChatMessageInsert = TablesInsert<'chat_messages'>
export type ChatMessageUpdate = TablesUpdate<'chat_messages'>

export type DocumentAsset = Tables<'document_assets'>
export type DocumentAssetInsert = TablesInsert<'document_assets'>
export type DocumentAssetUpdate = TablesUpdate<'document_assets'>

export type DocumentUser = Tables<'document_users'>
export type DocumentUserInsert = TablesInsert<'document_users'>
export type DocumentUserUpdate = TablesUpdate<'document_users'>

// Enum-like types for commonly used string fields
export type CallStatus = 'pending' | 'success' | 'failed'
export type PromptType = 'chat' | 'summarise' | 'glossary' | 'headings' | 'test' | 'test_headings' | 'test_enhancement' | 'pdf-to-html' | 'url-to-html' | 'reading_difficulty' | 'semantic-search' | 'page_to_html'
export type EnhancementType = 'summary' | 'glossary' | 'headings' | 'search' | 'semantic-search' | 'reading_difficulty' | 'tweet-thread'
export type MessageRole = 'user' | 'assistant' | 'system'

// Add additional convenience types here as needed
// For example:
// export type CustomViewType = { ... }
// export type SpecialOperationType = { ... }