#!/usr/bin/env npx tsx

/**
 * Script to generate database types with a warning banner
 * This wraps the supabase type generation to add a banner warning
 */

import { execSync } from 'child_process';
import { writeFileSync, readFileSync } from 'fs';
import { join } from 'path';

const BANNER = `/**
 * ⚠️ AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY ⚠️
 * 
 * This file is automatically generated by \`npm run db:types\`
 * Any manual changes will be overwritten on the next generation.
 * 
 * For manual type additions, use lib/types/database-extensions.ts
 * Import from database-extensions.ts instead of this file directly.
 */

`;

const OUTPUT_FILE = join(process.cwd(), 'lib/types/database-auto-generated.ts');

try {
  // Run supabase type generation
  console.log('Generating database types...');
  const generatedTypes = execSync('supabase gen types typescript --local', {
    encoding: 'utf-8',
  });

  // Prepend banner to the generated content
  const contentWithBanner = BANNER + generatedTypes;

  // Write to file
  writeFileSync(OUTPUT_FILE, contentWithBanner, 'utf-8');

  console.log('✅ Database types generated successfully with banner');
} catch (error) {
  console.error('❌ Failed to generate database types:', error);
  process.exit(1);
}